name: Feray Öztürk
<<<<<<< HEAD
description:
meta_description: ""
=======
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"
>>>>>>> f117b9f912c8c69fe4fdea58485cfedbe65fb0e2

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://ferayozturk.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://ferayozturk.github.io'
author:         'Feray Öztürk'
authorTwitter:  ''

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
